/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.mobile.pushnotifications.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Device service. Represents a row in the &quot;PushNotifications_Device&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.mobile.pushnotifications.model.impl.DeviceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.mobile.pushnotifications.model.impl.DeviceImpl}.
 * </p>
 *
 * @author Silvio Santos
 * @see Device
 * @see com.liferay.mobile.pushnotifications.model.impl.DeviceImpl
 * @see com.liferay.mobile.pushnotifications.model.impl.DeviceModelImpl
 * @generated
 */
public interface DeviceModel extends BaseModel<Device> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a device model instance should use the {@link Device} interface instead.
	 */

	/**
	 * Returns the primary key of this device.
	 *
	 * @return the primary key of this device
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this device.
	 *
	 * @param primaryKey the primary key of this device
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the device ID of this device.
	 *
	 * @return the device ID of this device
	 */
	@AutoEscape
	public String getDeviceId();

	/**
	 * Sets the device ID of this device.
	 *
	 * @param deviceId the device ID of this device
	 */
	public void setDeviceId(String deviceId);

	/**
	 * Returns the user ID of this device.
	 *
	 * @return the user ID of this device
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this device.
	 *
	 * @param userId the user ID of this device
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this device.
	 *
	 * @return the user uuid of this device
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this device.
	 *
	 * @param userUuid the user uuid of this device
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the application name of this device.
	 *
	 * @return the application name of this device
	 */
	@AutoEscape
	public String getApplicationName();

	/**
	 * Sets the application name of this device.
	 *
	 * @param applicationName the application name of this device
	 */
	public void setApplicationName(String applicationName);

	/**
	 * Returns the platform of this device.
	 *
	 * @return the platform of this device
	 */
	@AutoEscape
	public String getPlatform();

	/**
	 * Sets the platform of this device.
	 *
	 * @param platform the platform of this device
	 */
	public void setPlatform(String platform);

	/**
	 * Returns the register date of this device.
	 *
	 * @return the register date of this device
	 */
	public long getRegisterDate();

	/**
	 * Sets the register date of this device.
	 *
	 * @param registerDate the register date of this device
	 */
	public void setRegisterDate(long registerDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Device device);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Device> toCacheModel();

	@Override
	public Device toEscapedModel();

	@Override
	public Device toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}