/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.mobile.pushnotifications.model.impl;

import com.liferay.mobile.pushnotifications.model.Device;
import com.liferay.mobile.pushnotifications.model.DeviceModel;
import com.liferay.mobile.pushnotifications.model.DeviceSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Device service. Represents a row in the &quot;PushNotifications_Device&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.mobile.pushnotifications.model.DeviceModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DeviceImpl}.
 * </p>
 *
 * @author Silvio Santos
 * @see DeviceImpl
 * @see com.liferay.mobile.pushnotifications.model.Device
 * @see com.liferay.mobile.pushnotifications.model.DeviceModel
 * @generated
 */
@JSON(strict = true)
public class DeviceModelImpl extends BaseModelImpl<Device>
	implements DeviceModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a device model instance should use the {@link com.liferay.mobile.pushnotifications.model.Device} interface instead.
	 */
	public static final String TABLE_NAME = "PushNotifications_Device";
	public static final Object[][] TABLE_COLUMNS = {
			{ "deviceId", Types.VARCHAR },
			{ "userId", Types.BIGINT },
			{ "applicationName", Types.VARCHAR },
			{ "platform", Types.VARCHAR },
			{ "registerDate", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table PushNotifications_Device (deviceId VARCHAR(75) not null primary key,userId LONG,applicationName VARCHAR(75) null,platform VARCHAR(75) null,registerDate LONG)";
	public static final String TABLE_SQL_DROP = "drop table PushNotifications_Device";
	public static final String ORDER_BY_JPQL = " ORDER BY device.deviceId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY PushNotifications_Device.deviceId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.mobile.pushnotifications.model.Device"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.mobile.pushnotifications.model.Device"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.mobile.pushnotifications.model.Device"),
			true);
	public static long USERID_COLUMN_BITMASK = 1L;
	public static long DEVICEID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Device toModel(DeviceSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Device model = new DeviceImpl();

		model.setDeviceId(soapModel.getDeviceId());
		model.setUserId(soapModel.getUserId());
		model.setApplicationName(soapModel.getApplicationName());
		model.setPlatform(soapModel.getPlatform());
		model.setRegisterDate(soapModel.getRegisterDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Device> toModels(DeviceSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Device> models = new ArrayList<Device>(soapModels.length);

		for (DeviceSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.mobile.pushnotifications.model.Device"));

	public DeviceModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _deviceId;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setDeviceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _deviceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return Device.class;
	}

	@Override
	public String getModelClassName() {
		return Device.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("deviceId", getDeviceId());
		attributes.put("userId", getUserId());
		attributes.put("applicationName", getApplicationName());
		attributes.put("platform", getPlatform());
		attributes.put("registerDate", getRegisterDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String deviceId = (String)attributes.get("deviceId");

		if (deviceId != null) {
			setDeviceId(deviceId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String applicationName = (String)attributes.get("applicationName");

		if (applicationName != null) {
			setApplicationName(applicationName);
		}

		String platform = (String)attributes.get("platform");

		if (platform != null) {
			setPlatform(platform);
		}

		Long registerDate = (Long)attributes.get("registerDate");

		if (registerDate != null) {
			setRegisterDate(registerDate);
		}
	}

	@JSON
	@Override
	public String getDeviceId() {
		if (_deviceId == null) {
			return StringPool.BLANK;
		}
		else {
			return _deviceId;
		}
	}

	@Override
	public void setDeviceId(String deviceId) {
		_deviceId = deviceId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getApplicationName() {
		if (_applicationName == null) {
			return StringPool.BLANK;
		}
		else {
			return _applicationName;
		}
	}

	@Override
	public void setApplicationName(String applicationName) {
		_applicationName = applicationName;
	}

	@JSON
	@Override
	public String getPlatform() {
		if (_platform == null) {
			return StringPool.BLANK;
		}
		else {
			return _platform;
		}
	}

	@Override
	public void setPlatform(String platform) {
		_platform = platform;
	}

	@JSON
	@Override
	public long getRegisterDate() {
		return _registerDate;
	}

	@Override
	public void setRegisterDate(long registerDate) {
		_registerDate = registerDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public Device toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Device)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DeviceImpl deviceImpl = new DeviceImpl();

		deviceImpl.setDeviceId(getDeviceId());
		deviceImpl.setUserId(getUserId());
		deviceImpl.setApplicationName(getApplicationName());
		deviceImpl.setPlatform(getPlatform());
		deviceImpl.setRegisterDate(getRegisterDate());

		deviceImpl.resetOriginalValues();

		return deviceImpl;
	}

	@Override
	public int compareTo(Device device) {
		String primaryKey = device.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Device)) {
			return false;
		}

		Device device = (Device)obj;

		String primaryKey = device.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		DeviceModelImpl deviceModelImpl = this;

		deviceModelImpl._originalUserId = deviceModelImpl._userId;

		deviceModelImpl._setOriginalUserId = false;

		deviceModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Device> toCacheModel() {
		DeviceCacheModel deviceCacheModel = new DeviceCacheModel();

		deviceCacheModel.deviceId = getDeviceId();

		String deviceId = deviceCacheModel.deviceId;

		if ((deviceId != null) && (deviceId.length() == 0)) {
			deviceCacheModel.deviceId = null;
		}

		deviceCacheModel.userId = getUserId();

		deviceCacheModel.applicationName = getApplicationName();

		String applicationName = deviceCacheModel.applicationName;

		if ((applicationName != null) && (applicationName.length() == 0)) {
			deviceCacheModel.applicationName = null;
		}

		deviceCacheModel.platform = getPlatform();

		String platform = deviceCacheModel.platform;

		if ((platform != null) && (platform.length() == 0)) {
			deviceCacheModel.platform = null;
		}

		deviceCacheModel.registerDate = getRegisterDate();

		return deviceCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{deviceId=");
		sb.append(getDeviceId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", applicationName=");
		sb.append(getApplicationName());
		sb.append(", platform=");
		sb.append(getPlatform());
		sb.append(", registerDate=");
		sb.append(getRegisterDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.liferay.mobile.pushnotifications.model.Device");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>deviceId</column-name><column-value><![CDATA[");
		sb.append(getDeviceId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>applicationName</column-name><column-value><![CDATA[");
		sb.append(getApplicationName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>platform</column-name><column-value><![CDATA[");
		sb.append(getPlatform());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>registerDate</column-name><column-value><![CDATA[");
		sb.append(getRegisterDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Device.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { Device.class };
	private String _deviceId;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _applicationName;
	private String _platform;
	private long _registerDate;
	private long _columnBitmask;
	private Device _escapedModel;
}